# -*- coding: utf-8 -*-
"""mockdataaaaaa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pv4aOMZkt-s5ZcL69wImjG796T8_KU-L
"""

!pip install django djangorestframework pdfplumber easyocr python-magic --quiet
!pip install pydantic openpyxl faker pandas numpy matplotlib reportlab Pillow --quiet
!pip install pymupdf opencv-python-headless pytesseract --quiet
!apt-get install tesseract-ocr tesseract-ocr-fra -q
print('✅ All dependencies installed')

import pandas as pd
import numpy as np
import random
from faker import Faker
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import warnings
warnings.filterwarnings('ignore')

fake = Faker('fr_FR')
random.seed(42)
np.random.seed(42)

INSTITUTIONS = ['ENSTAB', 'FSEG Bizerte', 'ISSAT Mateur', 'ISG Bizerte', 'IPEST', 'FSHS Bizerte', 'INBMI']
SPECIALTIES  = ['Informatique', 'Genie Civil', 'Finance', 'Biologie', 'Chimie', 'Physique', 'Electronique', 'Management']
LEVELS       = ['L1', 'L2', 'L3', 'M1', 'M2']
GROUPS       = ['G1', 'G2', 'G3', 'G4']
TRANSPORT    = ['Transport universitaire', 'Vehicule personnel', 'Transports publics', 'A pied']

FIRST_NAMES = ['Ahmed','Mohamed','Youssef','Omar','Bilel','Sami','Amine','Khalil',
               'Nour','Fatma','Amira','Sana','Rania','Dorra','Ines','Malek',
               'Ayoub','Hamza','Tarek','Rym','Wafa','Hajer','Salma','Mariem']
LAST_NAMES  = ['Ben Ali','Trabelsi','Gharbi','Hamdi','Mansouri','Karoui','Jebali',
               'Chaabane','Mzoughi','Bensalem','Ferchichi','Nasr','Belhaj','Ayari']

N = 120

def rgrade(mean=12, std=3):
    return round(float(np.clip(np.random.normal(mean, std), 0, 20)), 2)

rows = []
for i in range(N):
    institution = random.choice(INSTITUTIONS)
    specialty   = random.choice(SPECIALTIES)
    level       = random.choice(LEVELS)
    group       = random.choice(GROUPS)
    first_name  = random.choice(FIRST_NAMES)
    last_name   = random.choice(LAST_NAMES)
    student_id  = f'UCAR-{institution[:3].upper()}-2024-{str(i+1).zfill(4)}'

    total_s1 = 60; abs_s1 = random.randint(0, 20); pres_s1 = total_s1 - abs_s1
    total_s2 = 60; abs_s2 = random.randint(0, 20); pres_s2 = total_s2 - abs_s2
    just_s1  = random.choice(['Oui', 'Non'])
    just_s2  = random.choice(['Oui', 'Non'])

    n_chimie  = rgrade(12, 3)
    n_physique= rgrade(11, 3.5)
    n_math    = rgrade(13, 3)
    n_fr      = rgrade(12, 2.5)
    n_en      = rgrade(13, 2)
    n_info    = rgrade(14, 3)
    n_bio     = rgrade(11.5, 3)
    n_stage   = rgrade(14, 2)

    avg_s1  = round(np.mean([n_chimie, n_physique, n_math, n_fr, n_en]), 2)
    avg_s2  = round(np.mean([n_info, n_bio, n_stage, n_math, n_en]), 2)
    avg_gen = round((avg_s1 + avg_s2) / 2, 2)

    if avg_gen >= 10:   outcome = 'Admis'
    elif avg_gen >= 8:  outcome = 'Rattrapage'
    else:               outcome = 'Ajourne'

    rows.append({
        'ID_Etudiant':            student_id,
        'Nom':                    last_name,
        'Prenom':                 first_name,
        'Genre':                  random.choice(['M', 'F']),
        'Annee de naissance':     random.randint(1998, 2005),
        'Etablissement':          institution,
        'Specialite':             specialty,
        'Niveau':                 level,
        'Groupe':                 group,
        'Seances totales S1':     total_s1,
        'Presences S1':           pres_s1,
        'Absences S1':            abs_s1,
        'Absences justifiees S1': just_s1,
        'Taux absence S1 (%)':    round(abs_s1 / total_s1 * 100, 1),
        'Seances totales S2':     total_s2,
        'Presences S2':           pres_s2,
        'Absences S2':            abs_s2,
        'Absences justifiees S2': just_s2,
        'Taux absence S2 (%)':    round(abs_s2 / total_s2 * 100, 1),
        'Note Chimie':            n_chimie,
        'Note Physique':          n_physique,
        'Note Mathematiques':     n_math,
        'Note Francais':          n_fr,
        'Note Anglais':           n_en,
        'Moyenne S1':             avg_s1,
        'Note Informatique':      n_info,
        'Note Biologie':          n_bio,
        'Note Stage/PFE':         n_stage,
        'Moyenne S2':             avg_s2,
        'Moyenne Generale':       avg_gen,
        'Resultat':               outcome,
        'Redoublement':           'Oui' if random.random() < 0.12 else 'Non',
        'Bourse':                 random.choice(['Oui', 'Non']),
        'Frais payes':            random.choice(['Oui', 'Non']),
        'Moyen de transport':     random.choice(TRANSPORT),
        'Possede un laptop':      random.choice(['Oui', 'Non']),
        'Stage effectue':         random.choice(['Oui', 'Non']) if level in ['L3','M1','M2'] else 'Non',
        'Situation post-diplome': random.choice(['Oui','Non','En cours']) if level == 'M2' else 'N/A',
    })

df = pd.DataFrame(rows)
print(f'✅ Generated {len(df)} student records with {len(df.columns)} columns')
df.head(3)

EXCEL_PATH = '/content/ucar_students_mock.xlsx'

wb = Workbook()
ws = wb.active
ws.title = 'Donnees Etudiants'

header_fill  = PatternFill('solid', start_color='1F3864')
header_font  = Font(color='FFFFFF', bold=True, name='Arial', size=10)
header_align = Alignment(horizontal='center', vertical='center', wrap_text=True)
thin = Border(left=Side(style='thin'), right=Side(style='thin'),
              top=Side(style='thin'), bottom=Side(style='thin'))
fill_even = PatternFill('solid', start_color='DCE6F1')
fill_odd  = PatternFill('solid', start_color='FFFFFF')

grade_cols = ['Note Chimie','Note Physique','Note Mathematiques','Note Francais',
              'Note Anglais','Note Informatique','Note Biologie','Note Stage/PFE',
              'Moyenne S1','Moyenne S2','Moyenne Generale']

columns = list(df.columns)
ws.row_dimensions[1].height = 40
for ci, col in enumerate(columns, 1):
    c = ws.cell(row=1, column=ci, value=col)
    c.fill = header_fill; c.font = header_font
    c.alignment = header_align; c.border = thin

for ri, row in df.iterrows():
    er = ri + 2
    fill = fill_even if ri % 2 == 0 else fill_odd
    for ci, col in enumerate(columns, 1):
        val = row[col]
        c = ws.cell(row=er, column=ci, value=val)
        c.fill = fill; c.border = thin
        c.alignment = Alignment(horizontal='center', vertical='center')
        if col in grade_cols and isinstance(val, (int, float)):
            c.font = Font(color='C00000', bold=True, name='Arial', size=9) if val < 10 else Font(color='375623', name='Arial', size=9)
        else:
            c.font = Font(name='Arial', size=9)

for ci, col in enumerate(columns, 1):
    max_len = max(len(str(col)), df[col].astype(str).str.len().max())
    ws.column_dimensions[get_column_letter(ci)].width = min(max_len + 2, 25)

ws.freeze_panes = 'A2'

# KPI Summary sheet
ws2 = wb.create_sheet('KPIs Resume')
for c, v in [('A1','KPI'), ('B1','Valeur')]:
    cell = ws2[c]; cell.value = v
    cell.fill = header_fill; cell.font = header_font
    cell.alignment = Alignment(horizontal='center')

kpi_rows = [
    ('Nombre total etudiants',    len(df)),
    ('Taux de reussite (%)',       round(len(df[df['Resultat']=='Admis'])/len(df)*100, 1)),
    ('Taux de redoublement (%)',   round(len(df[df['Redoublement']=='Oui'])/len(df)*100, 1)),
    ('Moyenne generale promo',     round(df['Moyenne Generale'].mean(), 2)),
    ('Taux absence moyen S1 (%)',  round(df['Taux absence S1 (%)'].mean(), 1)),
    ('Taux absence moyen S2 (%)',  round(df['Taux absence S2 (%)'].mean(), 1)),
    ('Boursiers (%)',              round(len(df[df['Bourse']=='Oui'])/len(df)*100, 1)),
]
for r, (k, v) in enumerate(kpi_rows, 2):
    ws2.cell(row=r, column=1, value=k).border = thin
    ws2.cell(row=r, column=2, value=v).border = thin
ws2.column_dimensions['A'].width = 35
ws2.column_dimensions['B'].width = 20

wb.save(EXCEL_PATH)
print(f'✅ Excel saved to {EXCEL_PATH}')

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import random

PDF_PATH = '/content/ucar_report_mock.pdf'

def generate_mock_pdf():
    c = canvas.Canvas(PDF_PATH, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "UNIVERSITE DE CARTHAGE — RAPPORT ANNUEL 2024")
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 75, "Etablissement: FSEG Bizerte | Annee: 2023-2024")

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, height - 120, "Indicateurs Cles de Performance (KPIs)")

    tr   = round(random.uniform(55, 85), 1)
    ps1  = round(random.uniform(70, 95), 1)
    ps2  = round(random.uniform(70, 95), 1)
    ta   = round(random.uniform(2, 10), 1)
    tred = round(random.uniform(5, 20), 1)
    mg   = round(random.uniform(10, 15), 2)
    ba   = random.randint(800000, 2000000)
    bc   = random.randint(600000, int(ba * 0.95))
    cpe  = random.randint(1500, 4000)
    ce   = random.randint(50000, 200000)
    ec   = random.randint(20000, 80000)

    kpis = [
        ("Taux de reussite",      f"{tr} %"),
        ("Taux de presence S1",   f"{ps1} %"),
        ("Taux de presence S2",   f"{ps2} %"),
        ("Taux d'abandon",        f"{ta} %"),
        ("Taux de redoublement",  f"{tred} %"),
        ("Moyenne generale",      f"{mg} / 20"),
        ("Budget alloue",         f"{ba} TND"),
        ("Budget consomme",       f"{bc} TND"),
        ("Cout par etudiant",     f"{cpe} TND"),
        ("Consommation energie",  f"{ce} kWh"),
        ("Empreinte carbone",     f"{ec} kg CO2"),
    ]

    c.setFont("Helvetica", 11)
    y = height - 150
    for label, value in kpis:
        c.drawString(70,  y, f"{label} :")
        c.drawString(310, y, value)
        y -= 22

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Document genere automatiquement — UCAR Pipeline 2024")
    c.save()
    print(f"✅ PDF generated: {PDF_PATH}")
    print(f"   reussite={tr}%  presence_s1={ps1}%  presence_s2={ps2}%  moyenne={mg}  redoublement={tred}%")

generate_mock_pdf()

from PIL import Image, ImageDraw, ImageFont
import random

IMG_PATH = '/content/ucar_report_mock.png'

def generate_mock_image():
    img  = Image.new('RGB', (1200, 800), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)

    try:
        font_title = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 22)
        font_body  = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18)
        font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 13)
    except:
        font_title = font_body = font_small = ImageFont.load_default()

    draw.rectangle([0, 0, 1200, 65], fill=(31, 56, 100))
    draw.text((20, 18), "UNIVERSITE DE CARTHAGE — RAPPORT ANNUEL 2024", font=font_title, fill=(255,255,255))
    draw.text((20, 80), "Etablissement: ISSAT Mateur  |  Annee: 2023-2024", font=font_body, fill=(40,40,40))

    draw.rectangle([20, 110, 1180, 138], fill=(200, 220, 255))
    draw.text((25, 115), "Indicateurs Cles de Performance", font=font_body, fill=(0,0,0))

    tr   = round(random.uniform(55, 85), 1)
    ps1  = round(random.uniform(70, 95), 1)
    ps2  = round(random.uniform(70, 95), 1)
    ta   = round(random.uniform(2, 10), 1)
    tred = round(random.uniform(5, 20), 1)
    mg   = round(random.uniform(10, 15), 2)
    ba   = random.randint(800000, 2000000)
    bc   = random.randint(600000, int(ba * 0.95))
    cpe  = random.randint(1500, 4000)
    ce   = random.randint(50000, 200000)
    ec   = random.randint(20000, 80000)

    # KEY FIX: write "Label : Value" as a SINGLE string on one line
    # so EasyOCR reads it as one detection — no split across columns
    kpis = [
        f"Taux de reussite : {tr} %",
        f"Taux de presence S1 : {ps1} %",
        f"Taux de presence S2 : {ps2} %",
        f"Taux d abandon : {ta} %",
        f"Taux de redoublement : {tred} %",
        f"Moyenne generale : {mg} / 20",
        f"Budget alloue : {ba} TND",
        f"Budget consomme : {bc} TND",
        f"Cout par etudiant : {cpe} TND",
        f"Consommation energie : {ce} kWh",
        f"Empreinte carbone : {ec} kg CO2",
    ]

    y = 148
    for i, line in enumerate(kpis):
        bg = (245, 248, 255) if i % 2 == 0 else (255, 255, 255)
        draw.rectangle([20, y, 1180, y + 36], fill=bg)
        draw.text((30, y + 8), line, font=font_body, fill=(30, 30, 30))
        y += 38

    draw.text((20, y + 15), "Document genere automatiquement — UCAR Pipeline 2024",
              font=font_small, fill=(150,150,150))

    img.save(IMG_PATH, dpi=(200, 200))
    print(f"✅ Image generated: {IMG_PATH}")
    print(f"   reussite={tr}%  presence_s1={ps1}%  presence_s2={ps2}%  moyenne={mg}  redoublement={tred}%")

generate_mock_image()

import os, sys
from pathlib import Path

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

PROJECT_DIR = Path('/content/ucar_project')
APP_DIR = PROJECT_DIR / 'ingestion'
PROJECT_DIR.mkdir(exist_ok=True)
APP_DIR.mkdir(exist_ok=True)
(APP_DIR / '__init__.py').write_text('')
(PROJECT_DIR / '__init__.py').write_text('')

(PROJECT_DIR / 'settings.py').write_text(
    'from pathlib import Path\n'
    'BASE_DIR = Path("/content/ucar_project")\n'
    'SECRET_KEY = "hack4ucar-dev"\n'
    'DEBUG = True\n'
    'INSTALLED_APPS = ["django.contrib.contenttypes", "django.contrib.auth", "ingestion"]\n'
    'DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "ucar.db"}}\n'
    'DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"\n'
)

(APP_DIR / 'models.py').write_text(
    'from django.db import models\n\n'
    'class KPIRecord(models.Model):\n'
    '    institution          = models.CharField(max_length=100)\n'
    '    source_file          = models.CharField(max_length=255)\n'
    '    file_type            = models.CharField(max_length=20)\n'
    '    created_at           = models.DateTimeField(auto_now_add=True)\n'
    '    taux_reussite        = models.FloatField(null=True, blank=True)\n'
    '    taux_presence_s1     = models.FloatField(null=True, blank=True)\n'
    '    taux_presence_s2     = models.FloatField(null=True, blank=True)\n'
    '    taux_abandon         = models.FloatField(null=True, blank=True)\n'
    '    taux_redoublement    = models.FloatField(null=True, blank=True)\n'
    '    moyenne_generale     = models.FloatField(null=True, blank=True)\n'
    '    budget_alloue        = models.FloatField(null=True, blank=True)\n'
    '    budget_consomme      = models.FloatField(null=True, blank=True)\n'
    '    cout_par_etudiant    = models.FloatField(null=True, blank=True)\n'
    '    consommation_energie = models.FloatField(null=True, blank=True)\n'
    '    empreinte_carbone    = models.FloatField(null=True, blank=True)\n'
    '    raw_text             = models.TextField(blank=True)\n\n'
    '    def __str__(self):\n'
    '        return f"{self.institution} - {self.source_file}"\n'
)

sys.path.insert(0, '/content/ucar_project')
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
import django
django.setup()
print('✅ Django configured')

import os
from django.core.management import call_command

os.chdir('/content/ucar_project')
call_command('makemigrations', 'ingestion')
call_command('migrate')
print('✅ Database migrated')

import os
import pdfplumber

def detect_file_type(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    ext_map = {
        '.pdf':  'pdf',
        '.png':  'image', '.jpg': 'image', '.jpeg': 'image', '.tiff': 'image',
        '.xlsx': 'excel', '.xls': 'excel',
        '.csv':  'csv'
    }
    ftype = ext_map.get(ext, 'unknown')
    if ftype == 'pdf':
        try:
            with pdfplumber.open(path) as pdf:
                text = ''.join(p.extract_text() or '' for p in pdf.pages[:2])
            ftype = 'pdf_scanned' if len(text.strip()) < 50 else 'pdf_digital'
        except:
            ftype = 'pdf_digital'
    return ftype

print('✅ Detector ready')
print('  Excel:', detect_file_type(EXCEL_PATH))
print('  PDF:  ', detect_file_type(PDF_PATH))
print('  Image:', detect_file_type(IMG_PATH))

import pdfplumber
import pandas as pd
import re
import cv2
import numpy as np
import fitz  # pymupdf
import io
from PIL import Image


def extract_from_pdf(path):
    """Digital PDFs — handles inline text + tables"""
    text = ''
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text(x_tolerance=3, y_tolerance=3) or ''
            # Also extract tables — institutions often export Word tables to PDF
            for table in (page.extract_tables() or []):
                for row in table:
                    clean_row = [str(c).strip() if c else '' for c in row]
                    if len(clean_row) == 2:
                        # "Label | Value" rows → convert to "label : value" for regex
                        page_text += f"\n{clean_row[0]} : {clean_row[1]}"
                    else:
                        page_text += '\n' + ' | '.join(clean_row)
            text += page_text + '\n'
    return text

def preprocess_for_ocr(img_array):
    """Grayscale + denoise + threshold + upscale — improves OCR on real scans"""
    gray     = cv2.cvtColor(img_array, cv2.COLOR_BGR2GRAY) if len(img_array.shape) == 3 else img_array
    denoised = cv2.fastNlMeansDenoising(gray, h=10)
    _, thresh = cv2.threshold(denoised, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    scaled   = cv2.resize(thresh, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    return scaled

def run_ocr(img_array):
    """EasyOCR on a preprocessed numpy image array"""
    import easyocr
    reader  = easyocr.Reader(['fr', 'en'], gpu=False)
    results = reader.readtext(img_array, detail=1)
    # Sort detections top-to-bottom, left-to-right
    results.sort(key=lambda r: (round(r[0][0][1] / 15) * 15, r[0][0][0]))
    raw = '\n'.join(r[1] for r in results)
    # Normalize OCR noise
    raw = re.sub(r"[''`´]", "'", raw)
    raw = re.sub(r'(\d)\s*[.,]\s*(\d)', r'\1.\2', raw)
    raw = re.sub(r'[ \t]+', ' ', raw)
    print(f"   🔍 OCR output ({len(raw)} chars):\n{raw[:600]}\n")
    return raw

def extract_from_image(path):
    """Image files — preprocess then OCR"""
    img_array = cv2.imread(path)
    processed = preprocess_for_ocr(img_array)
    return run_ocr(processed)

def extract_from_scanned_pdf(path):
    """Scanned PDFs — render each page as image then OCR"""
    doc = fitz.open(path)
    full_text = ''
    for page_num, page in enumerate(doc):
        mat = fitz.Matrix(2.5, 2.5)   # ~180 DPI — high enough for OCR
        pix = page.get_pixmap(matrix=mat, colorspace=fitz.csGRAY)
        img = Image.open(io.BytesIO(pix.tobytes("png")))
        img_array = np.array(img)
        print(f"   📄 OCR on scanned page {page_num + 1}...")
        full_text += run_ocr(img_array) + '\n'
    return full_text

def extract_from_excel(path):
    """Excel — fuzzy column matching handles inconsistent real-world headers"""
    sheets = pd.read_excel(path, sheet_name=None)
    parts  = []
    for name, sdf in sheets.items():
        parts.append(f'=== Feuille: {name} ===')
        parts.append(sdf.to_string(index=False))
    return '\n'.join(parts)

def extract_text(path, ftype):
    if ftype == 'pdf_digital':    return extract_from_pdf(path)
    elif ftype == 'pdf_scanned':  return extract_from_scanned_pdf(path)
    elif ftype == 'image':        return extract_from_image(path)
    elif ftype in ('excel','csv'): return extract_from_excel(path)
    return ''

print('✅ Extractors ready')
sample = extract_from_pdf(PDF_PATH)
print(f'\n📄 PDF raw text ({len(sample)} chars):\n{sample[:400]}')

import re

def normalize_for_regex(text: str) -> str:
    t = text.lower()

    # 1. Fix special OCR characters
    t = t.replace('œ', 'e').replace('æ', 'e')
    t = re.sub(r"[''`´]", "'", t)

    # 2. Fix "S1"/"S2" BEFORE digit rules (OCR reads S as 5)
    t = re.sub(r'\b51\b', 's1', t)
    t = re.sub(r'\b52\b', 's2', t)

    # 3. Collapse spaces/tabs — keep newlines
    t = re.sub(r'[ \t]+', ' ', t)

    # 4. Fix spaced decimals "72 . 3" → "72.3"
    t = re.sub(r'(\d)\s*\.\s*(\d)', r'\1.\2', t)

    # 5. Fix missing dot in 3-digit % values: "725%" → "72.5%"
    t = re.sub(r'\b([1-9]\d)(\d)\s*%', r'\1.\2%', t)

    # 6. Fix "moyenne" split across lines with value on next line
    t = re.sub(r'\b(\d{2})(\d{2})\s*\n\s*20\b', r'\1.\2 / 20', t)
    t = re.sub(r'(\d{1,2}[.,]\d{1,2})\s*\n\s*20\b', r'\1 / 20', t)

    # 7. Add space between letter and digit (skip s1/s2 context)
    t = re.sub(r'([a-rt-z%])(\d)', r'\1 \2', t)
    t = re.sub(r'(s)([3-9])', r'\1 \2', t)

    # 8. Handle thousands separators
    t = re.sub(r'(\d{1,3})([ ,])(\d{3})([ ,])(\d{3})', r'\1\3\5', t)
    t = re.sub(r'(\d{1,3})([ ,])(\d{3})(?!\d)', r'\1\3', t)

    # 9. Strip Arabic characters
    t = re.sub(r'[\u0600-\u06FF]+', ' ', t)

    # 10. Final space collapse
    t = re.sub(r'[ \t]+', ' ', t)

    return t


KPI_PATTERNS = {
    'taux_reussite': [
    r'taux\s+de\s+r[eé]ussite\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
    r'r[eé]ussite\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
    r'admis\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%',
    # ↓ new — handles OCR corrupting "r" → "(" or other non-letter characters
    r'taux\s+de\s+.{0,3}ussite\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
    ],
    'taux_presence_s1': [
        r'taux\s+de\s+pr[eé]s[eé]?n\w*\s+s1\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'pr[eé]s[eé]?n\w*\s+s1\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'taux\w*\s+pr[eé]s\w*\s+s1\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)',
        r'taux\w+\s+pr[eé]s\w*\s*s1\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)',
    ],
    'taux_presence_s2': [
        r'taux\s+de\s+pr[eé]s[eé]?n\w*\s+s2\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'pr[eé]s[eé]?n\w*\s+s2\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'taux\w*\s+pr[eé]s\w*\s+s2\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)',
        r'taux\w+\s+pr[eé]s\w*\s*s2\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)',
    ],
    'taux_abandon': [
        r"taux\s*d['\s]?abandon\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?",
        r"abandon\w*\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?",
        r"atondon\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?",
    ],
    'taux_redoublement': [
        r'taux\s+de\s+redoublement\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'redoublement\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
        r'redoub\w*\s*[:\-]?\s*([0-9]{1,3}(?:[.,][0-9]+)?)\s*%?',
    ],
    'moyenne_generale': [
        r'moyenne\s+g[eé]n[eé]rale\s*[:\-]?\s*([0-9]{1,2}(?:[.,][0-9]+)?)\s*(?:/\s*20)?',
        r'moyenneg[eé]n\w*\s*[:\-]?\s*([0-9]{1,2}(?:[.,][0-9]+)?)\s*(?:/\s*20)?',
        r'moyenne\s*g[eé]n?\w*\s*[:\-]?\s*([0-9]{1,2}(?:[.,][0-9]+)?)',
        r'moyenneg[eé]n\w*\s+([0-9]{1,2}[.,][0-9]+)\s*/\s*20',
    ],
    'budget_alloue': [
        r'budget\s+allou[eé]\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'budgetalloue?\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
    ],
    'budget_consomme': [
        r'budget\s+consomm[eé]\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'budget\w*somm\w*\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
    ],
    'cout_par_etudiant': [
        r'co[uû]t\s+par\s+[eé]tudiant\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'cout\w*\s+[eé]tud\w*\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'cout\s+p[ao]r\s+[eé]tud\w*\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',  # "por" OCR typo
    ],
    'consommation_energie': [
        r'consommation\s+[eé]nergie\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'consomm\w*[eé]nerg\w*\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'[eé]nergie\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
    ],
    'empreinte_carbone': [
        r'empreinte\s+carbone\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'empr\w*\s+carb\w*\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        r'carbone\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)',
        # value on next line after "empreinte carbone"
        r'empreinte\s+carbone[^\n]*\n\s*([0-9]+(?:[.,][0-9]+)?)',
    ],
}

def extract_kpis_regex(text: str) -> dict:
    results = {}
    tl = normalize_for_regex(text)
    print(f'\n   📝 Normalized text for regex:\n{tl}\n')
    for kpi, patterns in KPI_PATTERNS.items():
        found = None
        for p in patterns:
            m = re.search(p, tl, re.IGNORECASE | re.MULTILINE)
            if m:
                try:
                    raw   = m.group(1).strip().replace(' ', '').replace(',', '.')
                    found = float(raw)
                    # Sanity: percentages must be 0-100
                    if kpi in ('taux_reussite','taux_presence_s1','taux_presence_s2',
                               'taux_abandon','taux_redoublement') and found > 100:
                        found = None
                        continue
                except:
                    pass
                if found is not None:
                    break
        results[kpi] = found
        print(f"   {'✅' if found is not None else '❌'} {kpi}: {found}")
    return results


def extract_kpis_dataframe(data: pd.DataFrame) -> dict:
    """Compute KPIs directly from student-level DataFrame rows"""
    kpis = {}
    cols_lower = {c.lower(): c for c in data.columns}

    def find_col(*keywords):
        for kw in keywords:
            for cl, co in cols_lower.items():
                if kw in cl: return co
        return None

    res_col = find_col('resultat', 'outcome')
    if res_col:
        kpis['taux_reussite'] = round(
            data[res_col].astype(str).str.lower().isin(['admis']).sum() / len(data) * 100, 1)

    red_col = find_col('redoublement')
    if red_col:
        kpis['taux_redoublement'] = round(
            (data[red_col].astype(str).str.lower() == 'oui').sum() / len(data) * 100, 1)

    for sem in ['s1', 's2']:
        abs_col = find_col(f'absences {sem}')
        tot_col = find_col(f'seances totales {sem}', f'total {sem}')
        if abs_col and tot_col:
            pres = (data[tot_col] - data[abs_col]) / data[tot_col] * 100
            kpis[f'taux_presence_{sem}'] = round(pres.mean(), 1)

    avg_col = find_col('moyenne generale', 'moyenne gen')
    if avg_col:
        kpis['moyenne_generale'] = round(data[avg_col].mean(), 2)

    # Print extracted KPIs for visibility
    for k, v in kpis.items():
        print(f"   {'✅' if v is not None else '❌'} {k}: {v}")

    return kpis


# ── Self-test ────────────────────────────────────────────
ocr_test = """
taux de (eussite: 84.0 %
tauxde presne s1:84.8%
tauxde presne s2:72.6 %
tauxdatondon: 2.9%
taux de redoublement: 4.9%
moyennegenerale
13.83 / 20
budgetalloue: 1647203 tnd
budgetoonsomme
1156597 tnd
cout por etudiant: 3802 tnd
consommationenergie: 223628 kwh
empreinte carbone
85599 kg co2
"""
print("🧪 Self-test on OCR-corrupted text:")
test_result = extract_kpis_regex(ocr_test)
passed = sum(1 for v in test_result.values() if v is not None)
print(f'\n   {passed}/{len(test_result)} KPIs extracted in self-test')

from pydantic import BaseModel, validator
from typing import Optional

class KPISchema(BaseModel):
    institution:          str
    source_file:          str
    taux_reussite:        Optional[float] = None
    taux_presence_s1:     Optional[float] = None
    taux_presence_s2:     Optional[float] = None
    taux_abandon:         Optional[float] = None
    taux_redoublement:    Optional[float] = None
    moyenne_generale:     Optional[float] = None
    budget_alloue:        Optional[float] = None
    budget_consomme:      Optional[float] = None
    cout_par_etudiant:    Optional[float] = None
    consommation_energie: Optional[float] = None
    empreinte_carbone:    Optional[float] = None

    @validator('taux_reussite','taux_presence_s1','taux_presence_s2',
               'taux_abandon','taux_redoublement', pre=True)
    def pct(cls, v):
        if v is None: return None
        v = float(v)
        return round(v, 1) if 0 <= v <= 100 else None

    @validator('moyenne_generale', pre=True)
    def grade(cls, v):
        if v is None: return None
        v = float(v)
        return round(v, 2) if 0 <= v <= 20 else None

def validate_kpis(raw: dict, institution: str, source_file: str) -> KPISchema:
    raw.update({'institution': institution, 'source_file': source_file})
    return KPISchema(**raw)

def check_alerts(rec: KPISchema) -> list:
    alerts = []
    if rec.taux_reussite       is not None and rec.taux_reussite < 50:
        alerts.append(f'🔴 CRITIQUE — Taux de reussite: {rec.taux_reussite}% (seuil 50%)')
    if rec.taux_redoublement   is not None and rec.taux_redoublement > 20:
        alerts.append(f'🟠 ALERTE  — Taux de redoublement: {rec.taux_redoublement}%')
    if rec.moyenne_generale    is not None and rec.moyenne_generale < 10:
        alerts.append(f'🔴 CRITIQUE — Moyenne generale: {rec.moyenne_generale}/20')
    if rec.taux_presence_s1    is not None and rec.taux_presence_s1 < 75:
        alerts.append(f'🟠 ALERTE  — Presence S1 faible: {rec.taux_presence_s1}%')
    if rec.taux_presence_s2    is not None and rec.taux_presence_s2 < 75:
        alerts.append(f'🟠 ALERTE  — Presence S2 faible: {rec.taux_presence_s2}%')
    return alerts

print('✅ Pydantic validation + alerts ready')

from ingestion.models import KPIRecord

def save_to_db(rec: KPISchema, ftype: str, raw_text: str = '') -> int:
    obj = KPIRecord(
        institution          = rec.institution,
        source_file          = rec.source_file,
        file_type            = ftype,
        taux_reussite        = rec.taux_reussite,
        taux_presence_s1     = rec.taux_presence_s1,
        taux_presence_s2     = rec.taux_presence_s2,
        taux_abandon         = rec.taux_abandon,
        taux_redoublement    = rec.taux_redoublement,
        moyenne_generale     = rec.moyenne_generale,
        budget_alloue        = rec.budget_alloue,
        budget_consomme      = rec.budget_consomme,
        cout_par_etudiant    = rec.cout_par_etudiant,
        consommation_energie = rec.consommation_energie,
        empreinte_carbone    = rec.empreinte_carbone,
        raw_text             = raw_text[:3000],
    )
    obj.save()
    return obj.id

print('✅ DB save function ready')

def run_pipeline(file_path: str, institution: str) -> dict:
    print(f'📂 File: {os.path.basename(file_path)} | Institution: {institution}')

    ftype    = detect_file_type(file_path)
    raw_text = extract_text(file_path, ftype)
    print(f'   Type: {ftype} | Chars extracted: {len(raw_text)}')

    if ftype in ('excel', 'csv'):
        src_df   = pd.read_excel(file_path) if ftype == 'excel' else pd.read_csv(file_path)
        raw_kpis = extract_kpis_dataframe(src_df)
    else:
        raw_kpis = extract_kpis_regex(raw_text)

    validated = validate_kpis(raw_kpis, institution, os.path.basename(file_path))
    db_id     = save_to_db(validated, ftype, raw_text)
    alerts    = check_alerts(validated)

    print(f'   Saved as record #{db_id}')
    if alerts:
        for a in alerts: print(f'   {a}')
    else:
        print('   ✅ No alerts — all KPIs OK')

    return {'id': db_id, 'file_type': ftype, 'kpis': validated.dict(), 'alerts': alerts}

print('✅ Pipeline runner ready')

results = {}

test_cases = [
    (EXCEL_PATH, 'ENSTAB'),
    (PDF_PATH,   'FSEG Bizerte'),
    (IMG_PATH,   'ISSAT Mateur'),
]

for path, institution in test_cases:
    print(f"\n{'='*55}")
    print(f"▶ {path.split('/')[-1]} — {institution}")
    print('='*55)
    try:
        res = run_pipeline(path, institution)
        results[path] = res
        print(f"✅ SUCCESS — DB ID: {res['id']}")
    except Exception as e:
        import traceback; traceback.print_exc()
        results[path] = {'error': str(e)}

import matplotlib.pyplot as plt

results = {}
test_cases = [
    (EXCEL_PATH, 'ENSTAB'),
    (PDF_PATH,   'FSEG Bizerte'),
    (IMG_PATH,   'ISSAT Mateur'),
]

for path, institution in test_cases:
    print(f"\n{'='*55}")
    print(f"▶ {path.split('/')[-1]} — {institution}")
    print('='*55)
    try:
        res = run_pipeline(path, institution)
        results[path] = res
        print(f"✅ SUCCESS — DB ID: {res['id']}")
    except Exception as e:
        import traceback; traceback.print_exc()
        results[path] = {'error': str(e)}

# Build comparison table
KPI_KEYS = ['taux_reussite','taux_presence_s1','taux_presence_s2',
            'moyenne_generale','taux_redoublement','budget_alloue']
rows = []
for path, res in results.items():
    if 'error' in res:
        rows.append({'File': path.split('/')[-1], 'Type': 'ERROR', 'Status': res['error']})
        continue
    k      = res['kpis']
    filled = sum(1 for key in KPI_KEYS if k.get(key) is not None)
    rows.append({
        'File':             path.split('/')[-1],
        'Type':             res['file_type'],
        'Reussite (%)':     k.get('taux_reussite'),
        'Presence S1 (%)':  k.get('taux_presence_s1'),
        'Presence S2 (%)':  k.get('taux_presence_s2'),
        'Moyenne /20':      k.get('moyenne_generale'),
        'Redoublement (%)': k.get('taux_redoublement'),
        'Budget Alloue':    k.get('budget_alloue'),
        'Coverage':         f"{filled}/{len(KPI_KEYS)} KPIs",
        'Alerts':           len(res.get('alerts', [])),
    })

comparison_df = pd.DataFrame(rows)
display_df    = comparison_df.fillna('—')
print("📋 Pipeline Comparison Table:")
display(display_df)

# Dashboard chart
valid = [r for r in rows if 'Status' not in r]
if valid:
    labels  = [r['File'].replace('ucar_','').replace('_mock','') for r in valid]
    metrics = {
        'Reussite (%)':    [r['Reussite (%)']    or 0 for r in valid],
        'Presence S1 (%)': [r['Presence S1 (%)'] or 0 for r in valid],
        'Presence S2 (%)': [r['Presence S2 (%)'] or 0 for r in valid],
        'Moyenne (/20)×5': [(r['Moyenne /20'] or 0) * 5 for r in valid],
    }
    colors = ['#2196F3','#4CAF50','#FF9800','#9C27B0']
    x, width = range(len(labels)), 0.2
    fig, ax = plt.subplots(figsize=(12, 5))
    for i, (label, values) in enumerate(metrics.items()):
        offset = [xi + i * width for xi in x]
        bars   = ax.bar(offset, values, width, label=label, color=colors[i], alpha=0.85)
        for bar, val in zip(bars, values):
            if val > 0:
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.8,
                        f'{val:.1f}', ha='center', va='bottom', fontsize=8)
    ax.set_xticks([xi + width * 1.5 for xi in x])
    ax.set_xticklabels(labels, fontsize=11)
    ax.set_ylim(0, 115)
    ax.axhline(y=75, color='red',    linestyle='--', lw=1, alpha=0.5, label='Seuil 75%')
    ax.axhline(y=50, color='orange', linestyle='--', lw=1, alpha=0.5, label='Seuil 50%')
    ax.set_title('UCAR Pipeline — KPI Comparison by File Type', fontsize=13, fontweight='bold')
    ax.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig('/content/pipeline_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()
    print('✅ Dashboard saved to /content/pipeline_comparison.png')

import random
import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas as rl_canvas
from PIL import Image, ImageDraw, ImageFont

# ── Config ────────────────────────────────────────────────
INSTITUTIONS = [
    'ENSTAB', 'FSEG Bizerte', 'ISSAT Mateur',
    'ISG Bizerte', 'IPEST', 'FSHS Bizerte', 'INBMI'
]

def random_kpis():
    ba = random.randint(800000, 2000000)
    return {
        'taux_reussite':        round(random.uniform(45, 95), 1),
        'taux_presence_s1':     round(random.uniform(65, 98), 1),
        'taux_presence_s2':     round(random.uniform(65, 98), 1),
        'taux_abandon':         round(random.uniform(1, 15),  1),
        'taux_redoublement':    round(random.uniform(3, 25),  1),
        'moyenne_generale':     round(random.uniform(8, 16),  2),
        'budget_alloue':        ba,
        'budget_consomme':      random.randint(600000, int(ba * 0.95)),
        'cout_par_etudiant':    random.randint(1000, 5000),
        'consommation_energie': random.randint(40000, 250000),
        'empreinte_carbone':    random.randint(15000, 100000),
    }

# ── PDF generator ─────────────────────────────────────────
def generate_pdf(path, institution, kpis):
    c = rl_canvas.Canvas(path, pagesize=A4)
    w, h = A4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h-50, "UNIVERSITE DE CARTHAGE — RAPPORT ANNUEL 2024")
    c.setFont("Helvetica", 11)
    c.drawString(50, h-75, f"Etablissement: {institution} | Annee: 2023-2024")
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, h-120, "Indicateurs Cles de Performance (KPIs)")
    lines = [
        ("Taux de reussite",      f"{kpis['taux_reussite']} %"),
        ("Taux de presence S1",   f"{kpis['taux_presence_s1']} %"),
        ("Taux de presence S2",   f"{kpis['taux_presence_s2']} %"),
        ("Taux d'abandon",        f"{kpis['taux_abandon']} %"),
        ("Taux de redoublement",  f"{kpis['taux_redoublement']} %"),
        ("Moyenne generale",      f"{kpis['moyenne_generale']} / 20"),
        ("Budget alloue",         f"{kpis['budget_alloue']} TND"),
        ("Budget consomme",       f"{kpis['budget_consomme']} TND"),
        ("Cout par etudiant",     f"{kpis['cout_par_etudiant']} TND"),
        ("Consommation energie",  f"{kpis['consommation_energie']} kWh"),
        ("Empreinte carbone",     f"{kpis['empreinte_carbone']} kg CO2"),
    ]
    c.setFont("Helvetica", 11)
    y = h - 155
    for label, value in lines:
        c.drawString(70, y, f"{label} :")
        c.drawString(310, y, value)
        y -= 22
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Document genere automatiquement — UCAR Pipeline 2024")
    c.save()

# ── Image generator ───────────────────────────────────────
def generate_image(path, institution, kpis):
    img  = Image.new('RGB', (1200, 800), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    try:
        font_title = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 22)
        font_body  = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18)
        font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 13)
    except:
        font_title = font_body = font_small = ImageFont.load_default()

    draw.rectangle([0, 0, 1200, 65], fill=(31, 56, 100))
    draw.text((20, 18), "UNIVERSITE DE CARTHAGE — RAPPORT ANNUEL 2024", font=font_title, fill=(255,255,255))
    draw.text((20, 80), f"Etablissement: {institution}  |  Annee: 2023-2024", font=font_body, fill=(40,40,40))
    draw.rectangle([20, 110, 1180, 138], fill=(200, 220, 255))
    draw.text((25, 115), "Indicateurs Cles de Performance", font=font_body, fill=(0,0,0))

    lines = [
        f"Taux de reussite : {kpis['taux_reussite']} %",
        f"Taux de presence S1 : {kpis['taux_presence_s1']} %",
        f"Taux de presence S2 : {kpis['taux_presence_s2']} %",
        f"Taux d abandon : {kpis['taux_abandon']} %",
        f"Taux de redoublement : {kpis['taux_redoublement']} %",
        f"Moyenne generale : {kpis['moyenne_generale']} / 20",
        f"Budget alloue : {kpis['budget_alloue']} TND",
        f"Budget consomme : {kpis['budget_consomme']} TND",
        f"Cout par etudiant : {kpis['cout_par_etudiant']} TND",
        f"Consommation energie : {kpis['consommation_energie']} kWh",
        f"Empreinte carbone : {kpis['empreinte_carbone']} kg CO2",
    ]
    y = 148
    for i, line in enumerate(lines):
        draw.rectangle([20, y, 1180, y+36], fill=(245,248,255) if i%2==0 else (255,255,255))
        draw.text((30, y+8), line, font=font_body, fill=(30,30,30))
        y += 38

    draw.text((20, y+15), "Document genere automatiquement — UCAR Pipeline 2024",
              font=font_small, fill=(150,150,150))
    img.save(path, dpi=(200, 200))

# ── Excel generator ───────────────────────────────────────
def generate_excel(path, institution, n_students=80):
    import numpy as np
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    FIRST_NAMES = ['Ahmed','Mohamed','Youssef','Omar','Bilel','Sami','Amine',
                   'Nour','Fatma','Amira','Sana','Rania','Ines','Malek']
    LAST_NAMES  = ['Ben Ali','Trabelsi','Gharbi','Hamdi','Mansouri','Karoui',
                   'Chaabane','Mzoughi','Bensalem','Ferchichi','Nasr']
    LEVELS      = ['L1','L2','L3','M1','M2']
    SPECIALTIES = ['Informatique','Genie Civil','Finance','Biologie','Electronique']

    rows = []
    for i in range(n_students):
        total_s1 = 60; abs_s1 = random.randint(0, 20)
        total_s2 = 60; abs_s2 = random.randint(0, 20)
        grades   = [round(float(np.clip(np.random.normal(12,3),0,20)),2) for _ in range(8)]
        avg_s1   = round(sum(grades[:4])/4, 2)
        avg_s2   = round(sum(grades[4:])/4, 2)
        avg_gen  = round((avg_s1+avg_s2)/2, 2)
        rows.append({
            'ID_Etudiant':        f'UCAR-{institution[:3].upper()}-2024-{str(i+1).zfill(4)}',
            'Nom':                random.choice(LAST_NAMES),
            'Prenom':             random.choice(FIRST_NAMES),
            'Etablissement':      institution,
            'Specialite':         random.choice(SPECIALTIES),
            'Niveau':             random.choice(LEVELS),
            'Seances totales S1': total_s1,
            'Presences S1':       total_s1 - abs_s1,
            'Absences S1':        abs_s1,
            'Seances totales S2': total_s2,
            'Presences S2':       total_s2 - abs_s2,
            'Absences S2':        abs_s2,
            'Moyenne S1':         avg_s1,
            'Moyenne S2':         avg_s2,
            'Moyenne Generale':   avg_gen,
            'Resultat':           'Admis' if avg_gen>=10 else ('Rattrapage' if avg_gen>=8 else 'Ajourne'),
            'Redoublement':       'Oui' if random.random()<0.12 else 'Non',
        })

    df_ex = pd.DataFrame(rows)
    wb = Workbook()
    ws = wb.active
    ws.title = 'Donnees Etudiants'
    hfill = PatternFill('solid', start_color='1F3864')
    hfont = Font(color='FFFFFF', bold=True, name='Arial', size=10)
    thin  = Border(*[Side(style='thin')]*0,
                   left=Side(style='thin'), right=Side(style='thin'),
                   top=Side(style='thin'),  bottom=Side(style='thin'))
    cols  = list(df_ex.columns)
    for ci, col in enumerate(cols, 1):
        c = ws.cell(row=1, column=ci, value=col)
        c.fill=hfill; c.font=hfont
        c.alignment=Alignment(horizontal='center',vertical='center',wrap_text=True)
        c.border=thin
    for ri, row in df_ex.iterrows():
        fill = PatternFill('solid', start_color='DCE6F1' if ri%2==0 else 'FFFFFF')
        for ci, col in enumerate(cols, 1):
            c = ws.cell(row=ri+2, column=ci, value=row[col])
            c.fill=fill; c.border=thin
            c.alignment=Alignment(horizontal='center',vertical='center')
            c.font=Font(name='Arial', size=9)
    for ci, col in enumerate(cols, 1):
        ws.column_dimensions[get_column_letter(ci)].width = min(
            max(len(str(col)), df_ex[col].astype(str).str.len().max()) + 2, 25)
    ws.freeze_panes = 'A2'
    wb.save(path)
    return df_ex

# ══════════════════════════════════════════════════════════
# GENERATE ALL TEST FILES
# ══════════════════════════════════════════════════════════
random.seed(99)
N_EACH = 3   # ← change this to generate more files per type

test_cases = []
ground_truth = {}  # store expected values to verify pipeline accuracy

print("📁 Generating test files...\n")

for i in range(N_EACH):
    inst = INSTITUTIONS[i % len(INSTITUTIONS)]
    kpis = random_kpis()

    # PDF
    pdf_path = f'/content/test_pdf_{i+1}_{inst.replace(" ","_")}.pdf'
    generate_pdf(pdf_path, inst, kpis)
    test_cases.append((pdf_path, inst))
    ground_truth[pdf_path] = kpis
    print(f"  ✅ PDF:   {os.path.basename(pdf_path)}")

    # Image
    img_path = f'/content/test_img_{i+1}_{inst.replace(" ","_")}.png'
    generate_image(img_path, inst, kpis)
    test_cases.append((img_path, inst))
    ground_truth[img_path] = kpis
    print(f"  ✅ Image: {os.path.basename(img_path)}")

    # Excel
    xls_path = f'/content/test_xls_{i+1}_{inst.replace(" ","_")}.xlsx'
    generate_excel(xls_path, inst, n_students=60)
    test_cases.append((xls_path, inst))
    print(f"  ✅ Excel: {os.path.basename(xls_path)}")

print(f"\n✅ {len(test_cases)} files ready ({N_EACH} PDFs + {N_EACH} images + {N_EACH} Excel)\n")

# ══════════════════════════════════════════════════════════
# RUN PIPELINE ON ALL FILES
# ══════════════════════════════════════════════════════════
results = {}
for path, institution in test_cases:
    print(f"\n{'='*55}")
    print(f"▶ {os.path.basename(path)} — {institution}")
    print('='*55)
    try:
        res = run_pipeline(path, institution)
        results[path] = res
        print(f"✅ SUCCESS — DB ID: {res['id']}")
    except Exception as e:
        import traceback; traceback.print_exc()
        results[path] = {'error': str(e)}

# ══════════════════════════════════════════════════════════
# ACCURACY REPORT — compare pipeline output vs ground truth
# ══════════════════════════════════════════════════════════
print("\n\n" + "═"*70)
print("📊 ACCURACY REPORT — Pipeline vs Ground Truth")
print("═"*70)

kpi_map = {
    'taux_reussite':     'Reussite (%)',
    'taux_presence_s1':  'Presence S1 (%)',
    'taux_presence_s2':  'Presence S2 (%)',
    'taux_redoublement': 'Redoublement (%)',
    'moyenne_generale':  'Moyenne /20',
    'budget_alloue':     'Budget Alloue',
}

summary_rows = []
for path, res in results.items():
    fname = os.path.basename(path)
    ftype = res.get('file_type', 'error') if 'error' not in res else 'ERROR'
    if 'error' in res:
        summary_rows.append({'File': fname, 'Type': ftype, 'Coverage': '0/6',
                             'Avg Error': '—', 'Status': '❌ ERROR'})
        continue

    gt   = ground_truth.get(path)  # Excel has no ground truth KPIs (computed from data)
    got  = res['kpis']
    filled = sum(1 for k in kpi_map if got.get(k) is not None)

    if gt:
        errors = []
        for k in ['taux_reussite','taux_presence_s1','taux_presence_s2',
                  'taux_redoublement','moyenne_generale']:
            if got.get(k) is not None:
                errors.append(abs(got[k] - gt[k]))
        avg_err = round(sum(errors)/len(errors), 3) if errors else '—'
    else:
        avg_err = 'N/A (Excel)'

    summary_rows.append({
        'File':      fname,
        'Type':      ftype,
        'Coverage':  f"{filled}/6 KPIs",
        'Avg Error': avg_err,
        'Status':    '✅ OK' if filled >= 5 else '⚠️  Partial',
    })

summary_df = pd.DataFrame(summary_rows)
display(summary_df)

# Per-KPI accuracy across all non-Excel files
print("\n📌 Per-KPI accuracy (PDF + Image files only):\n")
for k in ['taux_reussite','taux_presence_s1','taux_presence_s2',
          'taux_redoublement','moyenne_generale']:
    errs = []
    for path, res in results.items():
        if 'error' in res or 'excel' in res.get('file_type',''):
            continue
        gt = ground_truth.get(path)
        if not gt: continue
        got_val = res['kpis'].get(k)
        if got_val is not None:
            errs.append(abs(got_val - gt[k]))
    if errs:
        print(f"  {k:25s} — avg error: {round(sum(errs)/len(errs),3):6.3f}  "
              f"max error: {round(max(errs),3):6.3f}  "
              f"extracted: {len(errs)}/{N_EACH*2} files")
    else:
        print(f"  {k:25s} — ❌ not extracted in any file")